# Generated by Django 2.2.5 on 2021-05-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolllist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.CharField(max_length=64)),
                ('classID', models.CharField(max_length=64)),
                ('group', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='examschedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=64)),
                ('dayOfWeek', models.IntegerField()),
                ('date', models.CharField(max_length=64)),
                ('classID', models.CharField(max_length=64)),
                ('className', models.CharField(max_length=64)),
                ('credit', models.IntegerField()),
                ('lectureName', models.CharField(max_length=64)),
                ('amount', models.IntegerField()),
                ('numberOfRoom', models.IntegerField()),
                ('CT', models.IntegerField()),
                ('auditorium', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classID', models.CharField(max_length=64)),
                ('dayOfWeek', models.IntegerField()),
                ('group', models.CharField(max_length=3)),
                ('courseID', models.CharField(max_length=64)),
                ('lectureID', models.IntegerField()),
                ('period', models.CharField(max_length=64)),
                ('className', models.CharField(max_length=64)),
                ('credit', models.IntegerField()),
                ('auditorium', models.CharField(max_length=64)),
                ('maxAMount', models.IntegerField()),
            ],
        ),
    ]
